"""Standardized WebAgent protocol contracts for orchestration.

This module centralizes P3 protocol definitions so the orchestration core can be
packaged as an SDK later without leaking product-specific service code.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, TypedDict

PROTOCOL_VERSION = "webagent.v1"
DEFAULT_PROFILE = "webagent_v1"
_ALLOWED_COMPLEXITY = {"low", "medium", "high"}
_ALLOWED_MODES = {"fast", "balanced", "deep"}
_ALLOWED_WORKER_KINDS = {"reason", "gather", "act", "synthesize"}


def _safe_int(value: Any, default: int) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _safe_float(value: Any, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


class WebAgentPlanNode(TypedDict, total=False):
    """One standardized worker node in WebAgent DAG."""

    id: str
    title: str
    kind: str
    mode: str
    objective: str
    tools: list[str]
    depends_on: list[str]
    deliverable: str


class WebAgentPlan(TypedDict, total=False):
    """Standardized DAG plan payload generated by planner model."""

    protocol: str
    strategy: str
    complexity: str
    assumptions: list[str]
    nodes: list[WebAgentPlanNode]
    expected_output: str


@dataclass(slots=True)
class OrchestratorConfig:
    """Runtime config for orchestration pipeline."""

    enabled: bool = False
    profile: str = DEFAULT_PROFILE
    planner_mode: str = "fast"
    executor_mode: str = "balanced"
    max_steps: int = 5
    max_workers: int = 3
    worker_timeout_s: int = 90
    worker_max_retries: int = 1
    worker_retry_backoff_ms: int = 600
    max_budget_usd: float = 0.0
    critique_enabled: bool = True
    critique_mode: str = "deep"
    dynamic_replan_enabled: bool = True
    max_replans: int = 1


def parse_orchestrator_config(
    runtime: dict[str, Any] | None,
    allowed_modes: set[str],
) -> OrchestratorConfig:
    """Parse runtime._runtime.orchestrator config with safe defaults."""
    if not runtime:
        return OrchestratorConfig(enabled=False)

    raw = runtime.get("orchestrator")
    if not isinstance(raw, dict):
        return OrchestratorConfig(enabled=False)

    enabled = bool(raw.get("enabled", False))
    profile = str(raw.get("profile", DEFAULT_PROFILE)).strip() or DEFAULT_PROFILE

    planner_mode = str(raw.get("planner_mode", "fast")).strip().lower()
    if planner_mode not in allowed_modes:
        planner_mode = "fast"

    executor_mode = str(raw.get("executor_mode", "balanced")).strip().lower()
    if executor_mode not in allowed_modes:
        executor_mode = "balanced"

    max_steps = _safe_int(raw.get("max_steps", 5), 5)
    max_steps = max(2, min(max_steps, 12))

    max_workers = _safe_int(raw.get("max_workers", 3), 3)
    max_workers = max(1, min(max_workers, 8))

    worker_timeout_s = _safe_int(raw.get("worker_timeout_s", 90), 90)
    worker_timeout_s = max(15, min(worker_timeout_s, 600))

    worker_max_retries = _safe_int(raw.get("worker_max_retries", 1), 1)
    worker_max_retries = max(0, min(worker_max_retries, 3))

    worker_retry_backoff_ms = _safe_int(raw.get("worker_retry_backoff_ms", 600), 600)
    worker_retry_backoff_ms = max(100, min(worker_retry_backoff_ms, 10_000))

    max_budget_usd = _safe_float(raw.get("max_budget_usd", 0.0), 0.0)
    max_budget_usd = max(0.0, min(max_budget_usd, 10_000.0))

    critique_enabled = bool(raw.get("critique_enabled", True))

    critique_mode = str(raw.get("critique_mode", "deep")).strip().lower()
    if critique_mode not in allowed_modes:
        critique_mode = "deep"

    dynamic_replan_enabled = bool(raw.get("dynamic_replan_enabled", True))

    max_replans = _safe_int(raw.get("max_replans", 1), 1)
    max_replans = max(0, min(max_replans, 3))

    return OrchestratorConfig(
        enabled=enabled,
        profile=profile,
        planner_mode=planner_mode,
        executor_mode=executor_mode,
        max_steps=max_steps,
        max_workers=max_workers,
        worker_timeout_s=worker_timeout_s,
        worker_max_retries=worker_max_retries,
        worker_retry_backoff_ms=worker_retry_backoff_ms,
        max_budget_usd=max_budget_usd,
        critique_enabled=critique_enabled,
        critique_mode=critique_mode,
        dynamic_replan_enabled=dynamic_replan_enabled,
        max_replans=max_replans,
    )


def build_plan_output_format(max_steps: int = 5) -> dict[str, Any]:
    """Build JSON schema for planner DAG output."""
    safe_steps = max(2, min(max_steps, 12))
    return {
        "type": "json_schema",
        "schema": {
            "type": "object",
            "properties": {
                "protocol": {"type": "string"},
                "strategy": {"type": "string"},
                "complexity": {
                    "type": "string",
                    "enum": ["low", "medium", "high"],
                },
                "assumptions": {
                    "type": "array",
                    "items": {"type": "string"},
                },
                "nodes": {
                    "type": "array",
                    "minItems": 2,
                    "maxItems": safe_steps,
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {"type": "string"},
                            "title": {"type": "string"},
                            "kind": {
                                "type": "string",
                                "enum": ["reason", "gather", "act", "synthesize"],
                            },
                            "mode": {
                                "type": "string",
                                "enum": ["fast", "balanced", "deep"],
                            },
                            "objective": {"type": "string"},
                            "tools": {
                                "type": "array",
                                "items": {"type": "string"},
                            },
                            "depends_on": {
                                "type": "array",
                                "items": {"type": "string"},
                            },
                            "deliverable": {"type": "string"},
                        },
                        "required": [
                            "id",
                            "title",
                            "kind",
                            "mode",
                            "objective",
                            "deliverable",
                        ],
                        "additionalProperties": False,
                    },
                },
                "expected_output": {"type": "string"},
            },
            "required": ["protocol", "strategy", "complexity", "nodes", "expected_output"],
            "additionalProperties": False,
        },
    }


def _normalize_node(item: dict[str, Any], index: int) -> WebAgentPlanNode:
    raw_kind = str(item.get("kind") or "gather").lower()
    kind = raw_kind if raw_kind in _ALLOWED_WORKER_KINDS else "gather"

    raw_mode = str(item.get("mode") or "balanced").lower()
    mode = raw_mode if raw_mode in _ALLOWED_MODES else "balanced"

    depends_on_raw = item.get("depends_on")
    depends_on = [
        str(dep).strip()
        for dep in depends_on_raw
        if isinstance(dep, str) and str(dep).strip()
    ] if isinstance(depends_on_raw, list) else []

    return WebAgentPlanNode(
        id=str(item.get("id") or f"node-{index}"),
        title=str(item.get("title") or f"节点 {index}"),
        kind=kind,
        mode=mode,
        objective=str(item.get("objective") or ""),
        tools=[
            str(tool_name)
            for tool_name in (item.get("tools") or [])
            if isinstance(tool_name, str)
        ],
        depends_on=depends_on,
        deliverable=str(item.get("deliverable") or ""),
    )


def _normalize_nodes(plan_obj: dict[str, Any]) -> list[WebAgentPlanNode]:
    nodes_raw = plan_obj.get("nodes")
    if isinstance(nodes_raw, list) and nodes_raw:
        nodes: list[WebAgentPlanNode] = []
        for index, item in enumerate(nodes_raw, start=1):
            if not isinstance(item, dict):
                continue
            nodes.append(_normalize_node(item, index))
        if nodes:
            return nodes

    steps_raw = plan_obj.get("steps")
    if isinstance(steps_raw, list) and steps_raw:
        nodes: list[WebAgentPlanNode] = []
        for index, item in enumerate(steps_raw, start=1):
            if not isinstance(item, dict):
                continue
            node = _normalize_node(item, index)
            if not node.get("depends_on") and index > 1:
                prev = nodes[index - 2]["id"] if len(nodes) >= 1 else f"node-{index-1}"
                node["depends_on"] = [prev]
            nodes.append(node)
        return nodes

    return []


def parse_webagent_plan(
    structured_output: Any,
    text_output: str = "",
) -> WebAgentPlan | None:
    """Parse planner output from structured payload or text fallback."""
    plan_obj: Any = None

    if isinstance(structured_output, dict):
        plan_obj = structured_output
    elif isinstance(structured_output, str):
        try:
            plan_obj = json.loads(structured_output)
        except json.JSONDecodeError:
            plan_obj = None

    if not isinstance(plan_obj, dict) and text_output.strip():
        try:
            plan_obj = json.loads(text_output)
        except json.JSONDecodeError:
            plan_obj = None

    if not isinstance(plan_obj, dict):
        return None

    nodes = _normalize_nodes(plan_obj)
    if not nodes:
        return None

    node_ids = {node["id"] for node in nodes}
    for node in nodes:
        depends = node.get("depends_on") or []
        node["depends_on"] = [dep for dep in depends if dep in node_ids and dep != node["id"]]

    complexity = str(plan_obj.get("complexity") or "medium").lower()
    if complexity not in _ALLOWED_COMPLEXITY:
        complexity = "medium"

    assumptions = plan_obj.get("assumptions")
    assumption_list = [
        str(value) for value in assumptions if isinstance(value, str)
    ] if isinstance(assumptions, list) else []

    return WebAgentPlan(
        protocol=str(plan_obj.get("protocol") or PROTOCOL_VERSION),
        strategy=str(plan_obj.get("strategy") or "decompose-and-execute"),
        complexity=complexity,
        assumptions=assumption_list,
        nodes=nodes,
        expected_output=str(plan_obj.get("expected_output") or ""),
    )


def list_plan_nodes(plan: WebAgentPlan, max_nodes: int = 12) -> list[WebAgentPlanNode]:
    """Return normalized nodes trimmed by max limit."""
    nodes = plan.get("nodes") or []
    normalized = [node for node in nodes if isinstance(node, dict)]
    return normalized[: max(1, max_nodes)]


def build_dag_layers(plan: WebAgentPlan, max_nodes: int = 12) -> list[list[WebAgentPlanNode]]:
    """Build topological layers for concurrent worker execution.

    Falls back to sequential layers if graph is invalid or cyclic.
    """
    nodes = list_plan_nodes(plan, max_nodes=max_nodes)
    if not nodes:
        return []

    node_map: dict[str, WebAgentPlanNode] = {
        str(node.get("id") or f"node-{index}"): node
        for index, node in enumerate(nodes, start=1)
    }

    indegree: dict[str, int] = {node_id: 0 for node_id in node_map}
    adjacency: dict[str, set[str]] = {node_id: set() for node_id in node_map}

    for node_id, node in node_map.items():
        deps = [
            dep for dep in (node.get("depends_on") or [])
            if isinstance(dep, str) and dep in node_map and dep != node_id
        ]
        unique_deps: list[str] = []
        seen: set[str] = set()
        for dep in deps:
            if dep in seen:
                continue
            seen.add(dep)
            unique_deps.append(dep)

        indegree[node_id] = len(unique_deps)
        for dep in unique_deps:
            adjacency[dep].add(node_id)

    ready = sorted([node_id for node_id, deg in indegree.items() if deg == 0])
    layers: list[list[WebAgentPlanNode]] = []
    visited = 0

    while ready:
        current = ready
        ready = []
        layer_nodes = [node_map[node_id] for node_id in current]
        layers.append(layer_nodes)

        for node_id in current:
            visited += 1
            for nxt in sorted(adjacency.get(node_id, set())):
                indegree[nxt] -= 1
                if indegree[nxt] == 0:
                    ready.append(nxt)

    if visited != len(node_map):
        return [[node] for node in nodes]

    return layers


def pick_execution_mode(
    plan: WebAgentPlan,
    default_mode: str,
    allowed_modes: set[str],
) -> str:
    """Pick final execution mode from plan complexity and node preferences."""
    if default_mode in allowed_modes:
        fallback = default_mode
    else:
        fallback = "balanced"

    nodes = plan.get("nodes") or []
    for node in nodes:
        if not isinstance(node, dict):
            continue
        mode = str(node.get("mode") or "").lower()
        if mode == "deep":
            return "deep"

    complexity = str(plan.get("complexity") or "medium").lower()
    if complexity == "high":
        return "deep"
    if complexity == "low":
        return "fast"
    return fallback


def compact_plan_for_prompt(plan: WebAgentPlan, max_steps: int = 8) -> str:
    """Render DAG into concise markdown for executor prompt injection."""
    nodes = list_plan_nodes(plan, max_nodes=max_steps)
    if not nodes:
        return "- 无可用计划节点"

    lines: list[str] = []
    for index, node in enumerate(nodes, start=1):
        title = str(node.get("title") or f"节点 {index}")
        mode = str(node.get("mode") or "balanced")
        kind = str(node.get("kind") or "gather")
        objective = str(node.get("objective") or "")
        depends_on = node.get("depends_on") or []
        dep_text = f" <- {', '.join(depends_on)}" if depends_on else ""
        lines.append(f"{index}. [{mode}/{kind}] {title} - {objective}{dep_text}")

    return "\n".join(lines) if lines else "- 无可用计划节点"


def summarize_plan_steps(plan: WebAgentPlan, max_steps: int = 8) -> list[dict[str, Any]]:
    """Return compact JSON-safe nodes for API/SSE metadata.

    Keep historical function name for backward compatibility.
    """
    nodes = list_plan_nodes(plan, max_nodes=max_steps)
    summary: list[dict[str, Any]] = []
    for node in nodes:
        summary.append(
            {
                "id": str(node.get("id") or ""),
                "title": str(node.get("title") or ""),
                "kind": str(node.get("kind") or ""),
                "mode": str(node.get("mode") or ""),
                "objective": str(node.get("objective") or ""),
                "depends_on": [
                    str(dep)
                    for dep in (node.get("depends_on") or [])
                    if isinstance(dep, str)
                ],
            }
        )
    return summary
