/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as LandingIndexRouteImport } from './routes/_landing.index'
import { Route as DashboardSqlReplRouteImport } from './routes/_dashboard.sql-repl'
import { Route as DashboardSqlExecutionLogRouteImport } from './routes/_dashboard.sql-execution-log'
import { Route as DashboardShowcaseRouteImport } from './routes/_dashboard.showcase'
import { Route as DashboardMemoryBlocksRouteImport } from './routes/_dashboard.memory-blocks'
import { Route as DashboardMapRouteImport } from './routes/_dashboard.map'
import { Route as DashboardGraphRouteImport } from './routes/_dashboard.graph'
import { Route as DashboardEntitiesRouteImport } from './routes/_dashboard.entities'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardAboutRouteImport } from './routes/_dashboard.about'
import { Route as DashboardEntitiesEntityIdRouteImport } from './routes/_dashboard.entities.$entityId'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardSqlReplRoute = DashboardSqlReplRouteImport.update({
  id: '/sql-repl',
  path: '/sql-repl',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSqlExecutionLogRoute =
  DashboardSqlExecutionLogRouteImport.update({
    id: '/sql-execution-log',
    path: '/sql-execution-log',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardShowcaseRoute = DashboardShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoryBlocksRoute = DashboardMemoryBlocksRouteImport.update({
  id: '/memory-blocks',
  path: '/memory-blocks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGraphRoute = DashboardGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEntitiesRoute = DashboardEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEntitiesEntityIdRoute =
  DashboardEntitiesEntityIdRouteImport.update({
    id: '/$entityId',
    path: '/$entityId',
    getParentRoute: () => DashboardEntitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof DashboardAboutRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/entities': typeof DashboardEntitiesRouteWithChildren
  '/graph': typeof DashboardGraphRoute
  '/map': typeof DashboardMapRoute
  '/memory-blocks': typeof DashboardMemoryBlocksRoute
  '/showcase': typeof DashboardShowcaseRoute
  '/sql-execution-log': typeof DashboardSqlExecutionLogRoute
  '/sql-repl': typeof DashboardSqlReplRoute
  '/': typeof LandingIndexRoute
  '/entities/$entityId': typeof DashboardEntitiesEntityIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof DashboardAboutRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/entities': typeof DashboardEntitiesRouteWithChildren
  '/graph': typeof DashboardGraphRoute
  '/map': typeof DashboardMapRoute
  '/memory-blocks': typeof DashboardMemoryBlocksRoute
  '/showcase': typeof DashboardShowcaseRoute
  '/sql-execution-log': typeof DashboardSqlExecutionLogRoute
  '/sql-repl': typeof DashboardSqlReplRoute
  '/': typeof LandingIndexRoute
  '/entities/$entityId': typeof DashboardEntitiesEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_dashboard/about': typeof DashboardAboutRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/entities': typeof DashboardEntitiesRouteWithChildren
  '/_dashboard/graph': typeof DashboardGraphRoute
  '/_dashboard/map': typeof DashboardMapRoute
  '/_dashboard/memory-blocks': typeof DashboardMemoryBlocksRoute
  '/_dashboard/showcase': typeof DashboardShowcaseRoute
  '/_dashboard/sql-execution-log': typeof DashboardSqlExecutionLogRoute
  '/_dashboard/sql-repl': typeof DashboardSqlReplRoute
  '/_landing/': typeof LandingIndexRoute
  '/_dashboard/entities/$entityId': typeof DashboardEntitiesEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/dashboard'
    | '/entities'
    | '/graph'
    | '/map'
    | '/memory-blocks'
    | '/showcase'
    | '/sql-execution-log'
    | '/sql-repl'
    | '/'
    | '/entities/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard'
    | '/entities'
    | '/graph'
    | '/map'
    | '/memory-blocks'
    | '/showcase'
    | '/sql-execution-log'
    | '/sql-repl'
    | '/'
    | '/entities/$entityId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_landing'
    | '/_dashboard/about'
    | '/_dashboard/dashboard'
    | '/_dashboard/entities'
    | '/_dashboard/graph'
    | '/_dashboard/map'
    | '/_dashboard/memory-blocks'
    | '/_dashboard/showcase'
    | '/_dashboard/sql-execution-log'
    | '/_dashboard/sql-repl'
    | '/_landing/'
    | '/_dashboard/entities/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_dashboard/sql-repl': {
      id: '/_dashboard/sql-repl'
      path: '/sql-repl'
      fullPath: '/sql-repl'
      preLoaderRoute: typeof DashboardSqlReplRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sql-execution-log': {
      id: '/_dashboard/sql-execution-log'
      path: '/sql-execution-log'
      fullPath: '/sql-execution-log'
      preLoaderRoute: typeof DashboardSqlExecutionLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/showcase': {
      id: '/_dashboard/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof DashboardShowcaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/memory-blocks': {
      id: '/_dashboard/memory-blocks'
      path: '/memory-blocks'
      fullPath: '/memory-blocks'
      preLoaderRoute: typeof DashboardMemoryBlocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/map': {
      id: '/_dashboard/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/graph': {
      id: '/_dashboard/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof DashboardGraphRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/entities': {
      id: '/_dashboard/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof DashboardEntitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/about': {
      id: '/_dashboard/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/entities/$entityId': {
      id: '/_dashboard/entities/$entityId'
      path: '/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof DashboardEntitiesEntityIdRouteImport
      parentRoute: typeof DashboardEntitiesRoute
    }
  }
}

interface DashboardEntitiesRouteChildren {
  DashboardEntitiesEntityIdRoute: typeof DashboardEntitiesEntityIdRoute
}

const DashboardEntitiesRouteChildren: DashboardEntitiesRouteChildren = {
  DashboardEntitiesEntityIdRoute: DashboardEntitiesEntityIdRoute,
}

const DashboardEntitiesRouteWithChildren =
  DashboardEntitiesRoute._addFileChildren(DashboardEntitiesRouteChildren)

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEntitiesRoute: typeof DashboardEntitiesRouteWithChildren
  DashboardGraphRoute: typeof DashboardGraphRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardMemoryBlocksRoute: typeof DashboardMemoryBlocksRoute
  DashboardShowcaseRoute: typeof DashboardShowcaseRoute
  DashboardSqlExecutionLogRoute: typeof DashboardSqlExecutionLogRoute
  DashboardSqlReplRoute: typeof DashboardSqlReplRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEntitiesRoute: DashboardEntitiesRouteWithChildren,
  DashboardGraphRoute: DashboardGraphRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardMemoryBlocksRoute: DashboardMemoryBlocksRoute,
  DashboardShowcaseRoute: DashboardShowcaseRoute,
  DashboardSqlExecutionLogRoute: DashboardSqlExecutionLogRoute,
  DashboardSqlReplRoute: DashboardSqlReplRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LandingRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
